"""add file_id to jobs

Revision ID: 5eb8f2119739
Revises: 3ca2365e239c
Create Date: 2026-06-03 14:35:51.311935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb8f2119739'
down_revision: Union[str, Sequence[str], None] = '3ca2365e239c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'file_id')
    # ### end Alembic commands ###
