"""add relationships

Revision ID: 743c975c1ae4
Revises: a70820696129
Create Date: 2026-06-03 03:30:48.909212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743c975c1ae4'
down_revision: Union[str, Sequence[str], None] = 'a70820696129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'])
    op.add_column('jobs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###
