"""expand jobs table

Revision ID: 50c0439f19c1
Revises: 88035c7a2483
Create Date: 2026-06-03 13:21:02.937010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c0439f19c1'
down_revision: Union[str, Sequence[str], None] = '88035c7a2483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('input_file_key', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('output_file_key', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'output_file_key')
    op.drop_column('jobs', 'input_file_key')
    # ### end Alembic commands ###
