"""expand files table

Revision ID: 88035c7a2483
Revises: faa16a3bb7f9
Create Date: 2026-06-03 13:02:15.194115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88035c7a2483'
down_revision: Union[str, Sequence[str], None] = 'faa16a3bb7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('files', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('files', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'created_at')
    op.drop_column('files', 'expires_at')
    op.drop_column('files', 'mime_type')
    op.drop_column('files', 'size_bytes')
    # ### end Alembic commands ###
